In [1]:
import pandas as pd
import seaborn as sns

In [4]:
df = pd.read_csv('trajectories_.csv',sep=",")
df

      Energy  density  assortativity  clustering
0   1.096893      0.0            0.0         0.0
1   1.096893      0.0            0.0         0.0
2   1.096609      0.0            0.0         0.0
3   1.096670      0.0            0.0         0.0
4   1.096695      0.0            0.0         0.0
5   1.096389      0.0            0.0         0.0
6   1.096524      0.0            0.0         0.0
7   1.096665      0.0            0.0         0.0
8   1.096803      0.0            0.0         0.0
9   1.097055      0.0            0.0         0.0
10  1.097062      0.0            0.0         0.0